In [4]:
import random
import pandas as pd
numbers = [i for i in range(100)]
data = pd.Series([random.choice(numbers) for _ in range(100)])
data.values

array([96, 89, 71, 56, 68, 34, 70, 13, 88, 14, 45, 41, 12, 11, 79, 78, 14,
       32, 95, 64,  4,  6, 36, 34, 36, 15, 18, 79, 47, 83, 36, 96, 24, 37,
       65, 89,  8, 54, 71, 23, 34, 11, 35, 72, 11, 92, 39, 19, 33, 59, 49,
       59, 14, 35,  0, 47, 89, 33, 72, 92,  1, 98, 80, 72, 64, 96, 73, 81,
       27, 27, 51, 60, 10, 35, 50,  5, 53, 12, 19, 93,  9, 56, 46, 29, 63,
       43, 31, 42, 13, 78, 10, 12, 51, 10, 98, 85, 77, 17, 16, 42],
      dtype=int64)

In [26]:
data

0     57
1      0
2     35
3     70
4     30
      ..
95    11
96    81
97     1
98    30
99    73
Length: 100, dtype: int64

In [43]:
min_value = data.iloc[0]
for k in data.values:
    if k < min_value: 
        min_value = k
print('Số nhỏ nhất ', min_value)

Số nhỏ nhất  0

In [44]:
max_value = data.iloc[0]
for j in data.values:
    if j > max_value:
        max_value = j
print('Số lớn nhất ',max_value)

Số lớn nhất  99

In [45]:
data.min()

0

In [47]:
max_value = data.loc[0]
min_value = data.loc[0]
for i in list(data.index):
    if max_value < data.loc[i]:
        max_value = data.loc[i]
    if min_value > data.loc[i]:
        min_value = data.loc[i]
print(max_value,min_value)

99 0

In [48]:
max_value = data.loc[0]
min_value = data.loc[0]
for index,val in list(data.items()):
    if max_value < val:
        max_value = val
    if min_value > val:
        min_value = val
print(max_value,min_value)

99 0

In [50]:
#data.count hoặc data.len
max_value = data.loc[0]
min_value = data.loc[0]
for i in range(data.count()):
    if max_value < data.iloc[i]:
        max_value = data.iloc[i]
    if min_value > data.iloc[i]:
        min_value = data.iloc[i]
print(max_value,min_value)

99 0

In [51]:
data.mean()

49.41

In [52]:
above_mean = 0
below_mean = 0
mean_val = data.mean()
for i in range(data.count()):
    if data.iloc[i] > mean_val:
        above_mean +=1
    else:
        below_mean +=1
print(above_mean,below_mean)

51 49

In [19]:
sum_value = 0
for x in data:
    sum_value = sum_value + x
print(sum_value)
average_value = sum_value / 100
print(average_value)
slgtn=0
slgtl=0
for a in data:
    if a < average_value:
        slgtn=slgtn + 1
print('Số lượng nhỏ hơn giá trị trung bình',slgtn)
for b in data:
    if b > average_value:
        slgtl=slgtl + 1
print('Số lượng lớn hơn giá trị trung bình',slgtl)

4941
49.41
Số lượng nhỏ hơn giá trị trung bình 49
Số lượng lớn hơn giá trị trung bình 51

In [28]:
slsc=0
for c in data:
    if c%2 == 0:
        slsc=slsc +1
print('Số lượng số chẵn',slsc)

Số lượng số chẵn 55

In [31]:
slsl=0
for d in data:
    if d %2 !=0:
        slsl = slsl +1
print('Số lượng số lẻ',slsl)

Số lượng số lẻ 45

In [32]:
slsa = 0
for e in data:
    if e <0:
        slsa = slsa +1
print('Số lượng số âm',slsa)

Số lượng số âm 0

In [34]:
slsd = 0
for f in data:
    if f > 0:
        slsd = slsd +1
print('Số lượng số dương',slsd)

Số lượng số dương 99

In [39]:
#Số lần xuất hiện các số trong Series
c=0
slxh={}
for a in range (len(data)):
    for b in data:
        if b == data.iloc[a]:
            c = c+1
    slxh [data.iloc[a]]=c
    c=0
print(slxh)

{57: 2, 0: 1, 35: 2, 70: 1, 30: 4, 8: 1, 74: 1, 88: 1, 67: 1, 28: 1, 43: 3, 52: 1, 72: 2, 11: 2, 62: 3, 64: 1, 95: 3, 26: 3, 90: 1, 58: 3, 71: 1, 7: 2, 59: 2, 40: 2, 55: 2, 18: 1, 32: 2, 39: 1, 85: 1, 97: 1, 54: 1, 96: 2, 4: 2, 66: 1, 84: 2, 33: 1, 47: 1, 2: 1, 49: 1, 68: 2, 36: 2, 73: 4, 15: 1, 46: 1, 6: 2, 23: 1, 5: 2, 29: 2, 3: 1, 10: 1, 42: 1, 75: 1, 99: 1, 86: 1, 76: 2, 91: 1, 92: 1, 48: 1, 82: 1, 25: 1, 31: 1, 60: 1, 56: 1, 65: 1, 81: 1, 1: 1}

In [56]:
# Tìm tần số xuất hiện của các phần tử trong Series
dicts = {i:0 for i in range(100)}

for i in range(data.count()):
    if data.iloc[i] in dicts.keys():
        dicts[data.iloc[i]]+=1
dicts
result = sorted(dicts.items(), key=lambda x: x[1], reverse = True)
#x[1] chỉ cột giá trị, x từng phần tử trong items; x[0] chỉ cột keys, reverse = True theo chiều giảm dần
result = dict(result)
result

{30: 4,
 73: 4,
 26: 3,
 43: 3,
 58: 3,
 62: 3,
 95: 3,
 4: 2,
 5: 2,
 6: 2,
 7: 2,
 11: 2,
 29: 2,
 32: 2,
 35: 2,
 36: 2,
 40: 2,
 55: 2,
 57: 2,
 59: 2,
 68: 2,
 72: 2,
 76: 2,
 84: 2,
 96: 2,
 0: 1,
 1: 1,
 2: 1,
 3: 1,
 8: 1,
 10: 1,
 15: 1,
 18: 1,
 23: 1,
 25: 1,
 28: 1,
 31: 1,
 33: 1,
 39: 1,
 42: 1,
 46: 1,
 47: 1,
 48: 1,
 49: 1,
 52: 1,
 54: 1,
 56: 1,
 60: 1,
 64: 1,
 65: 1,
 66: 1,
 67: 1,
 70: 1,
 71: 1,
 74: 1,
 75: 1,
 81: 1,
 82: 1,
 85: 1,
 86: 1,
 88: 1,
 90: 1,
 91: 1,
 92: 1,
 97: 1,
 99: 1,
 9: 0,
 12: 0,
 13: 0,
 14: 0,
 16: 0,
 17: 0,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 24: 0,
 27: 0,
 34: 0,
 37: 0,
 38: 0,
 41: 0,
 44: 0,
 45: 0,
 50: 0,
 51: 0,
 53: 0,
 61: 0,
 63: 0,
 69: 0,
 77: 0,
 78: 0,
 79: 0,
 80: 0,
 83: 0,
 87: 0,
 89: 0,
 93: 0,
 94: 0,
 98: 0}

In [9]:
df = pd.read_excel(r'C:\Users\Admin\resources\students.xlsx')
#thêm r để tránh hiểu \ là dấu escape

In [10]:
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5

In [11]:
df.shape
#kích thước bộ dữ liệu 10 dòng 12 cột

(10, 12)

In [14]:
df.head()
#hiển thị 5 dữ liệu đầu

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8

In [12]:
df.tail()
# hiển thị 5 dữ liệu cuối

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Mã học sinh  10 non-null     int64
 1   Họ tên       10 non-null     object
 2   Ngày sinh    10 non-null     datetime64[ns]
 3   Quê quán     10 non-null     object
 4   Toán         10 non-null     float64
 5   Lý           10 non-null     float64
 6   Hoá          10 non-null     float64
 7   Sinh         10 non-null     float64
 8   Văn          10 non-null     float64
 9   Sử           10 non-null     float64
 10  Địa          10 non-null     float64
 11  Tiếng Anh    10 non-null     float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(2)
memory usage: 1.1+ KB

In [15]:
df.describe()
#Các giá trị tính toán
#std độ lệch chuẩn không lệch quá nhiều so vs giá trị trung bình -> các giá trị xung quanh nó

,Mã học sinh,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh
count,1.000000e+01,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2.020521e+07,6.910000,7.080000,6.920000,6.180000,6.310000,5.750000,6.440000,6.510000
std,3.027650e+00,1.481328,1.015218,1.180207,1.966836,1.323673,2.147996,1.992319,1.674946
min,2.020521e+07,4.200000,5.600000,5.400000,2.000000,4.000000,2.000000,3.400000,3.800000
25%,2.020521e+07,5.875000,6.575000,6.100000,5.250000,5.500000,4.525000,5.000000,5.500000
50%,2.020521e+07,7.000000,7.000000,6.750000,6.650000,6.500000,5.700000,6.300000,6.250000
75%,2.020522e+07,7.875000,7.625000,7.450000,7.000000,6.925000,7.250000,7.950000,7.750000
max,2.020522e+07,9.300000,9.000000,8.800000,9.000000,8.500000,9.200000,9.500000,9.000000

In [16]:
df.drop(['Họ tên', 'Ngày sinh'],axis = 1)

   Mã học sinh    Quê quán  Toán   Lý  Hoá  Sinh  Văn  Sử   Địa  Tiếng Anh
0     20205210      Hà Nội   7.0  8.0  8.8   6.8  4.0  5.4  5.6        8.5
1     20205211  Quảng Bình   5.6  7.7  6.0   7.0  6.5  6.0  3.4        9.0
2     20205212      Hà Nam   4.2  6.5  5.4   8.0  7.0  7.5  4.3        5.5
3     20205213    Bắc Ninh   8.0  5.6  6.5   7.0  7.5  6.5  5.6        6.0
4     20205214   Thái Bình   9.3  5.8  7.5   4.5  6.5  4.5  7.8        3.8
5     20205215      Hà Nội   5.6  7.0  5.6   5.0  6.4  3.8  8.0        4.9
6     20205216    Nam Định   6.7  6.8  7.3   6.0  6.7  8.0  9.5        7.6
7     20205217    Bắc Ninh   7.5  9.0  7.0   2.0  5.2  2.0  7.0        6.5
8     20205218      Hà Nội   7.0  7.4  6.4   9.0  8.5  9.2  8.4        7.8
9     20205219      Hà Nội   8.2  7.0  8.7   6.5  4.8  4.6  4.8        5.5

In [24]:
#Học sinh ở từng tỉnh thành tham gia kì thi tốt nghiệp:
Que={}
for a in df.index:
    c=0
    for b in df['Quê quán']:
        if df['Quê quán'][a] == b:
            c+=1
    Que[df['Quê quán'][a]]=c
Que

{'Hà Nội': 4,
 'Quảng Bình': 1,
 'Hà Nam': 1,
 'Bắc Ninh': 2,
 'Thái Bình': 1,
 'Nam Định': 1}

In [39]:
#học sinh nhỏ tuổi nhất
b= df['Ngày sinh'].loc[0]
c= 0
for a in df.index:
    if df['Ngày sinh'][a] > b:
        b= df['Ngày sinh'][a]
        c=a
print(df['Mã học sinh'][c], df['Họ tên'][c])

20205212 Trần Trang Nhung

In [36]:
min(df['Ngày sinh'])

Timestamp('2000-01-25 00:00:00')

In [40]:
#học sinh nhiều tuổi nhất
b= df['Ngày sinh'].loc[0]
c= 0
for a in df.index:
    if df['Ngày sinh'][a] < b:
        b= df['Ngày sinh'][a]
        c=a
print(df['Mã học sinh'][c], df['Họ tên'][c])

20205214 Đặng Ngọc Sơn

In [46]:
#Tính điểm trung bình
df['Trung bình']= ((df['Toán']+ df['Văn'] + df['Tiếng Anh'])*2 +df['Lý']+ df['Hoá']+ df['Sinh']+df['Sử ']+df['Địa'])/11
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh,Trung bình
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5,6.690909
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0,6.572727
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5,5.918182
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0,6.745455
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8,6.300000
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9,5.745455
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6,7.236364
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5,5.945455
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8,7.909091
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5,6.236364

In [47]:
df['Khối A'] = df['Toán']+df['Lý']+ df['Hoá']
df['Khối A1'] = df['Toán']+df['Lý']+ df['Tiếng Anh']
df['Khối B'] = df['Toán']+df['Sinh']+ df['Hoá']
df['Khối C'] = df['Văn']+df['Sử ']+df['Địa']
df['Khối D']= df['Toán']+df['Văn']+(df['Tiếng Anh'])*2
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,Địa,Tiếng Anh,Trung bình,Khối A,Khối A1,Khối B,Khối C,Khối D
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,5.6,8.5,6.690909,23.8,23.5,22.6,15.0,28.0
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,3.4,9.0,6.572727,19.3,22.3,18.6,15.9,30.1
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,4.3,5.5,5.918182,16.1,16.2,17.6,18.8,22.2
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,5.6,6.0,6.745455,20.1,19.6,21.5,19.6,27.5
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,7.8,3.8,6.300000,22.6,18.9,21.3,18.8,23.4
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,8.0,4.9,5.745455,18.2,17.5,16.2,18.2,21.8
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,9.5,7.6,7.236364,20.8,21.1,20.0,24.2,28.6
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,7.0,6.5,5.945455,23.5,23.0,16.5,14.2,25.7
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,8.4,7.8,7.909091,20.8,22.2,22.4,26.1,31.1
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,4.8,5.5,6.236364,23.9,20.7,23.4,14.2,24.0

In [55]:
kq_khoiA={}
for a in df.index:
    if df['Khối A'][a] >= 23.5:
        c= 'Đậu'
    else:
        c='Trượt'
    kq_khoiA[a]=c
df['KQKhoiA']= kq_khoiA.values()
kq_khoiA1={}
for a in df.index:
    if df['Khối A1'][a] >= 22:
        c= 'Đậu'
    else:
        c='Trượt'
    kq_khoiA1[a]=c
df['KQKhoiA1']= kq_khoiA1.values()
kq_khoiB={}
for a in df.index:
    if df['Khối B'][a] >= 21.5:
        c= 'Đậu'
    else:
        c='Trượt'
    kq_khoiB[a]=c
df['KQKhoiB']= kq_khoiB.values()
kq_khoiC={}
for a in df.index:
    if df['Khối C'][a] >= 22.5:
        c= 'Đậu'
    else:
        c='Trượt'
    kq_khoiC[a]=c
df['KQKhoiC']= kq_khoiC.values()
kq_khoiD={}
for a in df.index:
    if df['Khối D'][a] >= 27.5:
        c= 'Đậu'
    else:
        c='Trượt'
    kq_khoiD[a]=c
df['KQKhoiD']= kq_khoiD.values()
df

,Mã học sinh,Họ tên,Ngày sinh,Quê quán,Toán,Lý,Hoá,Sinh,Văn,Sử,...,Khối A,Khối A1,Khối B,Khối C,Khối D,KQKhoiA,KQKhoiA1,KQKhoiB,KQKhoiC,KQKhoiD
0,20205210,Nguyễn Đức Bình,2000-03-10,Hà Nội,7.0,8.0,8.8,6.8,4.0,5.4,...,23.8,23.5,22.6,15.0,28.0,Đậu,Đậu,Đậu,Trượt,Đậu
1,20205211,Lê Minh Hoàng,2001-02-11,Quảng Bình,5.6,7.7,6.0,7.0,6.5,6.0,...,19.3,22.3,18.6,15.9,30.1,Trượt,Đậu,Trượt,Trượt,Đậu
2,20205212,Trần Trang Nhung,2002-07-05,Hà Nam,4.2,6.5,5.4,8.0,7.0,7.5,...,16.1,16.2,17.6,18.8,22.2,Trượt,Trượt,Trượt,Trượt,Trượt
3,20205213,Nguyễn Thị Linh,2000-12-17,Bắc Ninh,8.0,5.6,6.5,7.0,7.5,6.5,...,20.1,19.6,21.5,19.6,27.5,Trượt,Trượt,Đậu,Trượt,Đậu
4,20205214,Đặng Ngọc Sơn,2000-01-25,Thái Bình,9.3,5.8,7.5,4.5,6.5,4.5,...,22.6,18.9,21.3,18.8,23.4,Trượt,Trượt,Trượt,Trượt,Trượt
5,20205215,Hà Trung Kiên,2000-04-03,Hà Nội,5.6,7.0,5.6,5.0,6.4,3.8,...,18.2,17.5,16.2,18.2,21.8,Trượt,Trượt,Trượt,Trượt,Trượt
6,20205216,Võ Hoàng Yến,2000-06-21,Nam Định,6.7,6.8,7.3,6.0,6.7,8.0,...,20.8,21.1,20.0,24.2,28.6,Trượt,Trượt,Trượt,Đậu,Đậu
7,20205217,Hoàng Trung Sơn,2000-08-27,Bắc Ninh,7.5,9.0,7.0,2.0,5.2,2.0,...,23.5,23.0,16.5,14.2,25.7,Đậu,Đậu,Trượt,Trượt,Trượt
8,20205218,Nguyễn Văn Thành,2000-05-20,Hà Nội,7.0,7.4,6.4,9.0,8.5,9.2,...,20.8,22.2,22.4,26.1,31.1,Trượt,Đậu,Đậu,Đậu,Đậu
9,20205219,Nguyễn Thanh Oai,2000-05-25,Hà Nội,8.2,7.0,8.7,6.5,4.8,4.6,...,23.9,20.7,23.4,14.2,24.0,Đậu,Trượt,Đậu,Trượt,Trượt